#+TITLE: arduino-libraries
#+AUTHOR: Peter Polidoro
#+EMAIL: peterpolidoro@gmail.com

C++ libraries for running on Arduino and other embedded processors.

* Install and Setup Software on your Host Machine

** Arduino

   [[https://github.com/janelia-arduino/arduino_setup]]

** Git

   [[https://github.com/janelia-experimental-technology/git_setup]]

* Install These Arduino Libraries on your Host Machine

  Run Arduino IDE and go to File / Preferences and make note of 'Sketchbook
  location:'. On Linux and Mac OS X, it is usually located in ~/Arduino. On
  older versions of Windows, it may be located in ~/My\ Documents/Arduino. On
  newer versions of WIndows, it may be located in ~/Documents/Arduino.

** Linux or Mac OS X

*** Clone this Repository

    Open a terminal.

    #+BEGIN_SRC sh
      mkdir ~/git
      cd ~/git
      git clone https://github.com/janelia-arduino/arduino-libraries
      cd arduino-libraries
      git submodule init
      git submodule update
    #+END_SRC

*** Make Symbolic Links to Libraries

**** Using Bash

     Open a terminal.

     #+BEGIN_SRC sh
       mkdir ~/Arduino/libraries/
       find ~/git/arduino-libraries -maxdepth 1 -mindepth 1 -type d -print0 | xargs -0 ln -s -t ~/Arduino/libraries
     #+END_SRC

**** Using Python

***** Install and Setup Python if Necessary

      [[https://github.com/janelia-pypi/python_setup][Setup Python]]

***** Run Python Symbolic Link Installer

      Open a terminal.

      #+BEGIN_SRC sh
        cd ~/git/arduino-libraries
        python3 symlinks.py --install # Makes symbolic links to libraries in /home/<yourusername>/Arduino/
      #+END_SRC

** Windows

   Open Git Bash:

   (Use "Insert" key to paste into Git Bash)

   #+BEGIN_SRC sh
     cd ~/My\ Documents/Arduino/ # Older versions of Windows
     cd ~/Documents/Arduino/ # Newer versions of Windows
     mv libraries/ libraries2/ # Make copy of old libraries
     git clone https://github.com/janelia-arduino/arduino-libraries libraries
     cd libraries
     git submodule init
     git submodule update
     cd ..
     cp -r libraries2/. libraries/ # Add old libraries to new libraries if desired
     cd libraries
     git checkout . # Delete any old library code that conflicts with new library code
   #+END_SRC

* Compile Library Example and Upload to Board

** Teensy Board

   [[https://www.pjrc.com/teensy/td_usage.html]]

** Arduino Board

   [[https://www.arduino.cc/en/Guide/ArduinoMega2560]]

* Update These Arduino Libraries on your Host Machine

** Linux or Mac OS X

   #+BEGIN_SRC sh
     cd ~/git/arduino-libraries
     git submodule update --recursive --remote
   #+END_SRC

** Windows

   Open Git Bash:

   #+BEGIN_SRC sh
     cd ~/My\ Documents/Arduino/libraries # Older versions of Windows
     cd ~/Documents/Arduino/libraries # Newer versions of Windows
     git submodule update --recursive --remote
   #+END_SRC
